services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - $DUMP_SQL:/tmp/dump.sql
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=$DB
 
volumes:
  pgdata: